# 接口ID
logbackup_modBackupConfig:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 修改备份配置
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: POST
      # 请求地址
      address: /api/auth/v1/log/modBackupConfig
      # 请求头
      headers:
        Content-Type: application/json
        token: ${token}
        Referer: ${base_url}/sub-app-unity/syslogBackUp
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    logbackup_modBackupConfig_01:
      # 接口用例名称
      name: 修改备份配置
      # 接口用例描述
      description: 修改备份配置
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          backupTaskName: 终端日志备份修改
          nameDatabase: sas_v3_doc
          description: 终端日志备份-自动化测试修改
          retentionTime: 1
          firstExecutionTime: $GetTime(format=%Y-%m-%d %H:%M:%S;cal=h+1)
          intervalPeriod: 2
          cycleUnit: "2"
          retentionUnit: "2"
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { 'statusCode': 0 ,"msg": "success"}