# 接口ID
logbackup_queryBackupConfigByNameDatabase:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 按name_database查询备份配置
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: POST
      # 请求地址
      address: /api/auth/v1/log/queryBackupConfigByNameDatabase
      # 请求头
      headers:
        Content-Type: application/json
        token: ${token}
        Referer: ${base_url}/sub-app-unity/syslogBackUp
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    logbackup_queryBackupConfigByNameDatabase_01:
      # 接口用例名称
      name: 按name_database查询备份
      # 接口用例描述
      description: 按name_database查询备份
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          nameDatabase: sas_v3_doc
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { 'statusCode': 0 ,"msg": "success"}
        # 提取变量
        extract:
          - name: id     #变量名称
            # jsonpath表达式
            jsonpath: $.data.id