# 接口ID
sysconfig_update:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 系统配置修改
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: POST
      # 请求地址
      address: /api/system/v1/system/updateInfoByPropKey
      # 请求头
      headers:
        Content-Type: application/x-www-form-urlencoded
        token: ${token}
        Referer: ${base_url}/sub-app-unity/systemConfig
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    sysconfig_update_01:
      # 接口用例名称
      name: 系统配置修改-修改账号锁定时间-修改成功
      # 接口用例描述
      description: 系统配置修改-修改账号锁定时间-修改成功
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          updateInfo: '{"${propKey}": "25"}'
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { 'statusCode': 0 }
          # 数据库校验
          dbcheck:
            - type: mysql
              sql: select propValue from `bms-general-aa`.t_sys_param_config tspc where propKey = '${propKey}'
              result:
                - path: $.propValue
                  value: 25
    # 接口用例ID
    sysconfig_update_02:
      # 接口用例名称
      name: 系统配置修改-修改账号锁定时间-修改值为非数字格式
      # 接口用例描述
      description: 系统配置修改-修改账号锁定时间-修改值为非数字格式
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          updateInfo: '{"${propKey}": "自动化测试"}'
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { 'statusCode': -1}
    # 接口用例ID
    sysconfig_update_03:
      # 接口用例名称
      name: 系统配置修改-参数不存在
      # 接口用例描述
      description: 系统配置修改-参数不存在
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          updateInfo: '{"自动化测试": "自动化测试"}'
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { 'statusCode': -1}