# 接口ID
sysconfig_getValueByPropKey:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 根据propKey获取对应的propValue
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: POST
      # 请求地址
      address: /api/system/v1/system/getValueByPropKey
      # 请求头
      headers:
        Content-Type: application/x-www-form-urlencoded
        token: ${token}
        Referer: ${base_url}/sub-app-unity/systemConfig
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    sysconfig_getValueByPropKey_01:
      # 接口用例名称
      name: 根据propKey获取对应的propValue-存在的propKey
      # 接口用例描述
      description: 根据propKey获取对应的propValue-存在的propKey
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          propKey: ${propKey1}
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: {'statusCode': 0, 'data':{'propValue': '111111'}}
    # 接口用例ID
    sysconfig_getValueByPropKey_02:
      # 接口用例名称
      name: 根据propKey获取对应的propValue-不存在的propKey
      # 接口用例描述
      description: 根据propKey获取对应的propValue-不存在的propKey
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          propKey: test
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { 'statusCode': 0, 'data': {} }