# 接口ID
usersync_syncConfig_delete:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 删除同步配置
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: DELETE
      # 请求地址
      address: /api/usersync/v1/syncConfig
      # 请求头
      headers:
        Content-Type: application/json
        token: ${token}
        Referer: ${base_url}/sub-app-unity/userSync
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    usersync_syncConfig_delete_01:
      # 接口用例名称
      name: 删除单个同步配置
      # 接口用例描述
      description: 删除一个同步配置
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          ids: ${syncConfigid;type=str}
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: {"statusCode": 0,"msg": "success"}