# 接口ID
usersync_syncConfig_list:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 同步列表搜索
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: POST
      # 请求地址
      address: /api/usersync/v1/syncConfig
      # 请求头
      headers:
        Content-Type: application/json
        token: ${token}
        Referer: ${base_url}/sub-app-unity/userSync
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    usersync_syncConfig_list_01:
      # 接口用例名称
      name: 同步配置列表搜索-无搜索条件
      # 接口用例描述
      description: 不输入搜索条件，点击搜索，查看数据源列表
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          pageNum: 1
          pageSize: 20
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: {"statusCode": 0,"msg": "success"}
    # 接口用例ID
    usersync_syncConfig_list_02:
      # 接口用例名称
      name: 同步配置列表搜索-按同步配置名称搜索
      # 接口用例描述
      description: 输入同步配置名称，点击搜索，查看同步配置列表
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          pageNum: 1
          pageSize: 20
          filters:
            syncName: 自动化测试同步配置
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { "statusCode": 0,"msg": "success" }
          # jsonpath校验
          jsonpath:
            - path: $.data.list[0].syncName
              value: 自动化测试同步配置
              type: in
        # 提取变量
        extract:
          - name: syncConfigid     #变量名称
            # jsonpath表达式
            jsonpath: $.data.list[0].id