# 接口ID
usersync_config_searchbyconfigId:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 根据数据源ID精确查找数据源
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: get
      # 请求地址
      address: /api/usersync/v1/config/${id}
      # 请求头
      headers:
        Content-Type: application/json
        token: ${token}
        Referer: ${base_url}/sub-app-unity/userSync
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    usersync_config_searchbyconfigId_01:
      # 接口用例名称
      name: 根据id查看数据源配置成功
      # 接口用例描述
      description: 输入正确的数据源id，查看数据源配置
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { "statusCode": 0,"msg": "success" , "data": {"id": '${id}', "name": '${name}'}}