# 接口ID
usersync_configs:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 数据源列表搜索
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: get
      # 请求地址
      address: /api/usersync/v1/configs
      # 请求头
      headers:
        Content-Type: application/json
        token: ${token}
        Referer: ${base_url}/sub-app-unity/userSync
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    usersync_configs_01:
      # 接口用例名称
      name: 数据源列表搜索-无搜索条件
      # 接口用例描述
      description: 不输入搜索条件，点击搜索，查看数据源列表
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          pageNum: '1'
          pageSize: '20'
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: {"statusCode": 0,"msg": "success"}
    # 接口用例ID
    usersync_configs_02:
      # 接口用例名称
      name: 数据源列表搜索-按数据源名称搜索
      # 接口用例描述
      description: 输入数据源名称，点击搜索，查看数据源列表
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          pageNum: '1'
          pageSize: '20'
          filters: '{"name":"自动化测试70.235数据源"}'
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: { "statusCode": 0,"msg": "success" }
          # jsonpath校验
          jsonpath:
            - path: $.data.list[0].name
              value: 自动化测试70.235数据源
              type: in
        # 提取变量
        extract:
          - name: id     #变量名称
            # jsonpath表达式
            jsonpath: $.data.list[0].id
          - name: name     #变量名称
            # jsonpath表达式
            jsonpath: $.data.list[0].name