# 接口ID
usersync_config_test:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 测试数据源配置
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: post
      # 请求地址
      address: /api/usersync/v1/config/test
      # 请求头
      headers:
        Content-Type: application/json
        token: ${token}
        Referer: ${base_url}/sub-app-unity/userSync
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    usersync_config_test_01:
      # 接口用例名称
      name: 测试LADP数据源配置成功
      # 接口用例描述
      description: 填写正确的LDAP数据源配置，点击测试
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          #数据源类型
          type: domain
          #数据源配置
          configs: "{\"name\":\"自动化测试70.235数据源修改\",\"host\":\"192.168.70.235\",\"port\":\"389\",\"username\":\"xiantest\\\\administrator\",\"password\":\"Ws-123456abcd\",\"base\":\"DC=xiantest,DC=com\",\"org\":\"ou=北京明朝万达\",\"isEncrypt\":false,\"userFilter\":\"\",\"groupFilter\":\"\",\"isIncrement\":false}"
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: {"statusCode": 0,"msg": "success"}