# 接口ID
sysemailconfig_getparaminfo:
  # 接口基本信息
  ApiInfo:
    # 接口名称
    api_name: 系统邮箱配置查询
    # 基础URL:https://192.168.148.174:31000
    base_url: ${base_url}
    # 请求信息
    request:
      # 请求类型
      method: POST
      # 请求地址
      address: /api/system/v1/system/getSysEmailParamInfo
      # 请求头
      headers:
        Content-Type: application/x-www-form-urlencoded
        token: ${token}
        Referer: ${base_url}/sub-app-unity/systemEmailConfig
  # 接口用例，填写接口发送数据、前置操作、后置操作，发送请求时将接口基本信息与接口数据组合
  ApiData:
    # 接口用例ID
    sysemailconfig_getparaminfo_01:
      # 接口用例名称
      name: 系统邮箱配置查询
      # 接口用例描述
      description: 系统邮箱配置查询
      # 请求信息，包括data，file
      request:
        # 请求数据
        data:
          sysParamKey: 系统邮箱配置
          paramType: 系统邮箱
      # 后置操作
      postProcessors:
        # 断言
        assert:
          # 状态码校验
          code: 200
          # 返回值校验
          response: [{"propName":"系统服务器地址"}]