# 运行项目
project_name: 统一管理平台

# 环境信息
base_url: https://192.168.148.174:31000

#全局登录接口
logincase: login_01

# 数据库类型
db_type: mysql
# 数据库相关配置
mysql_db:
  host: 192.168.148.174
  user: root
  password: ws-123456
  port: 3306

# redis相关配置
redis:
  host: 192.168.148.174
  port: 6379
  password: unity2.0@wondersoft

# kafka相关配置
kafka:
  bootstrap-servers: 192.168.148.174:9094

# 用例路径,列表形式
casedata_path:

# 证书文件
cert:
  - example.crt
  - example.key

# 邮件配置
email:
  #是否发送邮件，默认不发送
  sendemail: false
  # 发件服务器
  sendserver: smtp.wondersoft.cn
  # 端口号
  port: 25
  # 发件人
  sender:
  # 发件人密码
  senderPwd:
  # 收件人，多个收件人用分号隔开
  receiver: